[pytest]
minversion = 6.0
addopts = --strict-markers --tb=short -vv
asyncio_default_fixture_loop_scope = function
testpaths = tests
pythonpath = . src
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    asyncio: mark test functions as requiring asyncio
    authenticator: mark tests related to authenticator functionality
